services:
  redis:
    image: redis/redis-stack:latest
    environment:
      REDIS_ARGS: "--maxmemory 1gb --maxmemory-policy allkeys-lru"
    ports:
      - "127.0.0.1:6379:6379"  # Bind to localhost only
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    volumes:
      - redis_data:/data


volumes:
  redis_data:
  